import { INodeType, INodeTypeDescription } from "n8n-workflow";

import {
	accountingContactFields,
	accountingContactOperations,
	categoryFields,
	categoryOperations,
	checkAccountFields,
	checkAccountOperations,
	checkAccountTransactionFields,
	checkAccountTransactionOperations,
	communicationWayFields,
	communicationWayOperations,
	contactAddressFields,
	contactAddressOperations,
	contactCustomFieldFields,
	contactCustomFieldOperations,
	contactCustomFieldSettingFields,
	contactCustomFieldSettingOperations,
	contactFieldFields,
	contactFieldOperations,
	contactFields,
	contactOperations,
	countryFields,
	countryOperations,
	creditNoteFields,
	creditNoteOperations,
	creditNotePosFields,
	creditNotePosOperations,
	exportFields,
	exportOperations,
	invoiceFields,
	invoiceOperations,
	layoutFields,
	layoutOperations,
	orderFields,
	orderOperations,
	orderPoOperations,
	orderPosOperations,
	orderPosFields,
	partFields,
	partOperations,
	reportFields,
	reportOperations,
	tagFields,
	tagOperations,
	tagRelationFields,
	tagRelationOperations,
	unityFields,
	unityOperations,
	voucherFields,
	voucherOperations,
	voucherPoFields,
	voucherPoOperations,
	voucherPosOperations,
	voucherPosFields,
	basicsOperations,
	basicsFields,
} from "./descriptions";

export class SevDesk implements INodeType {
	description: INodeTypeDescription = {
		displayName: "sevDesk",
		name: "sevDesk",
		group: ["output"],
		version: 1,
		subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
		description: "Consume the sevDesk API",
		icon: "file:sevDesk.svg",
		defaults: {
			name: "sevDesk",
		},
		inputs: ["main"],
		outputs: ["main"],
		credentials: [
			{
				name: "sevDeskApi",
				required: true,
			},
		],
		requestDefaults: {
			baseURL: "https://my.sevdesk.de/api/{{$credentials.apiVersion}}/",
			url: "",
			headers: {
				Accept: "application/json",
				"Content-Type": "application/json",
			},
		},
		properties: [
			// Standard resource selection
			{
				displayName: "Resource",
				name: "resource",
				type: "options",
				noDataExpression: true,
				default: "contact",
				options: [
					{
						name: "AccountingContact",
						value: "accountingContact",
					},
					{
						name: "Basic",
						value: "basics",
					},
					{
						name: "Category",
						value: "category",
					},
					{
						name: "CheckAccount",
						value: "checkAccount",
					},
					{
						name: "CheckAccountTransaction",
						value: "checkAccountTransaction",
					},
					{
						name: "CommunicationWay",
						value: "communicationWay",
					},
					{
						name: "Contact",
						value: "contact",
					},
					{
						name: "Contact Address",
						value: "contactAddress",
					},
					{
						name: "Contact Custom Field",
						value: "contactCustomField",
					},
					{
						name: "Contact Custom Field Setting",
						value: "contactCustomFieldSetting",
					},
					{
						name: "Contact Field",
						value: "contactField",
					},
					{
						name: "Country",
						value: "country",
					},
					{
						name: "Credit Note",
						value: "creditNote",
					},
					{
						name: "Credit Note Po",
						value: "creditNotePos",
					},
					{
						name: "Export",
						value: "export",
					},
					{
						name: "Invoice",
						value: "invoice",
					},
					{
						name: "Layout",
						value: "layout",
					},
					{
						name: "Order",
						value: "order",
					},
					{
						name: "Order Position",
						value: "orderPos",
					},
					{
						name: "OrderPo",
						value: "orderPo",
					},
					{
						name: "Part",
						value: "part",
					},
					{
						name: "Report",
						value: "report",
					},
					{
						name: "Tag",
						value: "tag",
					},
					{
						name: "Tag Relation",
						value: "tagRelation",
					},
					{
						name: "Unit",
						value: "unit",
					},
					{
						name: "Voucher",
						value: "voucher",
					},
					{
						name: "VoucherPo",
						value: "voucherPo",
					},
				],
			},
			...contactOperations,
			...contactFields,
			...contactAddressOperations,
			...contactAddressFields,
			...contactCustomFieldOperations,
			...contactCustomFieldFields,
			...contactCustomFieldSettingOperations,
			...contactCustomFieldSettingFields,
			...contactFieldOperations,
			...contactFieldFields,
			...countryOperations,
			...countryFields,
			...categoryOperations,
			...categoryFields,
			...communicationWayOperations,
			...communicationWayFields,
			...accountingContactOperations,
			...accountingContactFields,
			...unityOperations,
			...unityFields,
			...orderOperations,
			...orderFields,
			...orderPosOperations,
			...orderPosFields,
			...orderPoOperations,
			...partOperations,
			...partFields,
			...checkAccountOperations,
			...checkAccountFields,
			...checkAccountTransactionOperations,
			...checkAccountTransactionFields,
			...creditNoteOperations,
			...creditNoteFields,
			...creditNotePosOperations,
			...creditNotePosFields,
			...exportOperations,
			...exportFields,
			...tagOperations,
			...tagFields,
			...tagRelationOperations,
			...tagRelationFields,
			...invoiceOperations,
			...invoiceFields,
			...layoutOperations,
			...layoutFields,
			...reportOperations,
			...reportFields,
			...voucherOperations,
			...voucherFields,
			...voucherPoOperations,
			...voucherPoFields,
			...voucherPosOperations,
			...voucherPosFields,
			...basicsOperations,
			...basicsFields,
		],
	};
}
